### ISSUE TITLE
[Bug]: verdaccio-memory@10.4.2 regression - TypeError: import___vite_browser_external.default.dirname is not a function

### ISSUE THREAD

**Issue by andrii-bodnar** [verdaccio/verdaccio#5828]
### What happened?

Hello!

The latest release of `verdaccio-memory` (**v10.4.2**) fails to start in Node.js environments. It appears that the recent migration from Babel to Vite 8 has resulted in Node.js built-in modules (specifically `path`) being incorrectly shimmed with browser-external mocks in the CommonJS output.

When the plugin attempts to resolve a directory path, it throws a `TypeError` because the shimmed `path` object does not contain Node.js functions like `dirname`.

**To Reproduce**
1. Install `verdaccio` and `verdaccio-memory@10.4.2` globally or locally in a Node.js environment (reproducible on Node 20, 22, and 24).
2. Start Verdaccio with a config that uses the `memory` storage plugin.
3. Attempt to publish a package or start the server.
4. See error: `TypeError: import___vite_browser_external.default.dirname is not a function`

**Logs & Environment**
* **Version:** `verdaccio-memory@10.4.2`
* **Node version:** `24.14.1` (also occurring on 22)
* **Failing CI Link:** https://github.com/lingui/js-lingui/actions/runs/24721928129/job/72312696050
* **Workflow:** https://github.com/lingui/js-lingui/blob/next/.github/workflows/release-test.yml
* **Config:** https://github.com/lingui/js-lingui/blob/next/.github/verdaccio/config.yaml

**Stack Trace:**
```text
fatal--- uncaught exception, please report this
TypeError: import___vite_browser_external.default.dirname is not a function
    at /opt/hostedtoolcache/node/24.14.1/x64/lib/node_modules/verdaccio-memory/lib/memory-handler.js:72:53
    at process.processTicksAndRejections (node:internal/process/task_queues:85:11)
```

**Additional Context**
This regression was introduced in the **10.4.2** release (specifically following the "Migrated all packages from Babel + Jest to Vite 8 + Vitest" change). 

Pinning `verdaccio-memory@10.4.1` in the workflow resolves the issue.

### Version

6.x (Stable)

### Version details

Latest

### Node.js Version

24.x.x (LTS)

### Package manager

yarn

### Operating system

linux

### Have I checked other issues?

- [x] I have searched existing issues

**Comment by mbtools** [comment]
The latest version of verdaccio-memory with esm support is 14.0.0-next-9.14. Can you try this, please?

**Comment by andrii-bodnar** [comment]
In my workflow, I have the following:

```
npm i -g verdaccio verdaccio-auth-memory verdaccio-memory
```

Do I need to specify the 14.0.0-next-9.14 version explicitly for all the packages? It's a significant update through a few major versions, so I'm unsure if it will require additional changes.

The main issue is that it worked on the previous version (10.4.1). I believe it's a regression in version 10.4.2.

**Comment by mbtools** [comment]
Yes it's a regression. You can either wait for the fix or try v14 which has been moved to vite (and better memfs) long time ago.

**Comment by andrii-bodnar** [comment]
@mbtools thanks for confirming that! I will probably temporarily pin the `10.4.1` version in my workflow.

**Comment by juanpicado** [comment]
Sorry my bad ... I will fix it later

**Comment by juanpicado** [comment]
verdaccio-memory@10.4.3

**Comment by andrii-bodnar** [comment]
@mbtools @juanpicado thank you for the quick response and fix!
